task:
    resource: AppBundle\Controller\TaskController
    type:     rest

dash:
    resource: AppBundle\Controller\DashController
    type:     annotation
    
default:
    resource: AppBundle\Controller\DefaultController
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"