<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskListRepository extends EntityRepository
{
    public function findTaskListWithTask($event, $completed) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT partial tl.{id, name}, partial t.{id, name}
                                    FROM AppBundle:TaskList tl JOIN tl.tasks t');
//        $consulta->setParameter('ciudad', 'barcelona');
//        $consulta->setParameter('fecha', '201X-XX-XX 00:00:00');
        return $query->getResult();
    }
}
